{{- define "power-lines-data-service.container-fixtures" -}}
name: {{ .Chart.Name }}-fixtures
{{- end -}}

{{- define "power-lines-data-service.container-results" -}}
name: {{ .Chart.Name }}-results
args: 
  {{- toYaml .Values.container.resultsArgs | nindent 12 }}
{{- end -}}

{{- define "power-lines-data-service.container-results-all" -}}
name: {{ .Chart.Name }}-results-all
args: 
  {{- toYaml .Values.container.resultsAllArgs | nindent 12 }}
{{- end -}}
