{{- define "power-lines-data-service.container-fixtures" -}}
name: {{ .Values.name }}-fixtures
envFrom:
- configMapRef:
    name: {{ .Values.name }}
{{- end -}}

{{- define "power-lines-data-service.container-results" -}}
name: {{ .Values.name }}-results
args: 
  {{- toYaml .Values.container.resultsArgs | nindent 12 }}
envFrom:
- configMapRef:
    name: {{ .Values.name }}
{{- end -}}

{{- define "power-lines-data-service.container-results-all" -}}
name: {{ .Values.name }}-results-all
args: 
  {{- toYaml .Values.container.resultsAllArgs | nindent 12 }}
envFrom:
- configMapRef:
    name: {{ .Values.name }}
{{- end -}}
