{{- include "helm-library.configmap" (list . "power-lines-data-service.configmap") -}}
{{- define "power-lines-data-service.configmap" -}}
data:
  Message__Host: {{ quote .Values.message.host }}
  Message__Port: {{ quote .Values.message.port }}
  Message__Username: {{ quote .Values.message.username }}
  Message__Password: {{ quote .Values.message.password }}
  Message__FixtureQueue: {{ quote .Values.message.fixtureQueue }}
  Message__ResultQueue: {{ quote .Values.message.resultQueue }}
  COMPlus_EnableDiagnostics: {{ quote .Values.container.comPlusEnableDiagnostics }}
  ASPNETCORE_ENVIRONMENT: {{ quote .Values.environment }}
{{- end -}}
