{{- include "helm-library.cron-job" (list . "power-lines-data-service.cron-job") -}}
{{- define "power-lines-data-service.cron-job" -}}
spec:
  jobTemplate: 
    spec:
      template:
        spec:          
          containers:
          - {{ include "helm-library.container" (list . "power-lines-data-service.container-fixtures") | nindent 12 }}
          - {{ include "helm-library.container" (list . "power-lines-data-service.container-results") | nindent 12 }}
{{- end -}}
