{{- include "helm-library.cron-job" (list . "power-lines-data-service.cron-job-fixtures") -}}
{{- define "power-lines-data-service.cron-job-fixtures" -}}
metadata:
  name: {{.Values.name }}-fixtures
spec:
  successfulJobsHistoryLimit: 1
  jobTemplate: 
    spec:
      template:
        spec:          
          containers:
          - {{ include "helm-library.container" (list . "power-lines-data-service.container-fixtures") | nindent 12 }}
{{- end -}}
