{{- include "helm-library.cron-job" (list . "power-lines-data-service.cron-job-results-all") -}}
{{- define "power-lines-data-service.cron-job-results-all" -}}
metadata:
  name: {{.Values.name }}-results-all
spec:
  successfulJobsHistoryLimit: 1
  schedule: {{.Values.cronJob.resultsAllSchedule }}
  jobTemplate: 
    spec:
      template:
        spec:
          containers:
          - {{ include "helm-library.container" (list . "power-lines-data-service.container-results-all") | nindent 12 }}
{{- end -}}
