version: '3.7'
services:
  power-lines-data-service:
    build: 
      target: development
    image: power-lines-data-service-test
    container_name: power-lines-data-service-test
    entrypoint: dotnet test ./PowerLinesDataService.Tests/PowerLinesDataService.Tests.csproj
