version: '3.7'
services:
  power-lines-data-service:
    build: 
      context: .
      target: development-env
    environment: 
      Message__Host: power-lines-message  
    volumes:
      - ./PowerLinesDataService:/PowerLinesDataService

networks:
  default:
    external:
      name: power-lines
