services:
  power-lines-data-service:
    build:
      target: development
    environment: 
      MESSAGE__HOST: power-lines-message
      MESSAGE__PORT: 5672
      MESSAGE__USERNAME: rabbitmq
      MESSAGE__PASSWORD: rabbitmq
      MESSAGE__FIXTUREQUEUE: fixtures
      MESSAGE__RESULTQUEUE: results
    depends_on: 
      power-lines-message:
        condition: service_healthy
    volumes:
      - ./PowerLinesDataService:/home/dotnet/PowerLinesDataService
    networks:
      - power-lines

  power-lines-message:
    image: rabbitmq:3-management-alpine
    container_name: power-lines-message
    hostname: power-lines-message
    environment:
      RABBITMQ_ERLANG_COOKIE: rabbitmq
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - power-lines
    healthcheck:
      test: rabbitmq-diagnostics -q ping --erlang-cookie rabbitmq
      interval: 10s
      retries: 5
      start_period: 1s
      timeout: 10s

networks:
  power-lines:
    driver: bridge
    name: power-lines
