services:
  power-lines-data-service:
    build:
      target: development
    environment: 
      Message__Host: power-lines-message
      Message__Port: 5672
      Message__Username: rabbitmq
      Message__Password: rabbitmq
      Message__FixtureQueue: fixtures
      Message__ResultQueue: results
    depends_on: 
      - power-lines-message
    volumes:
      - ./PowerLinesDataService:/home/dotnet/PowerLinesDataService

  power-lines-message:
    image: rabbitmq:3-management-alpine
    container_name: power-lines-message
    hostname: power-lines-message
    environment:
      RABBITMQ_ERLANG_COOKIE: rabbitmq
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "15672:15672"
      - "5672:5672"

networks:
  power-lines:
    driver: bridge
    name: power-lines
