version: '3.7'
services:
  power-lines-data-service-test:
    build: 
      context: .
      target: test-env
    image: power-lines-data-service-test
    container_name: power-lines-data-service-test
