container:
  image: power-lines-data-service
  resourceTier: M
  comPlusEnableDiagnostics: 0  
  command: ["dotnet"]
  args: ["PowerLinesDataService.dll", "--fixtures"]
  resultsArgs: ["PowerLinesDataService.dll", "--results"]
  resultsAllArgs: ["PowerLinesDataService.dll", "--results", "--all"]
  skipDefault: true

configMap:
  environment: production

message:
  host: services.lynxmagnus.com
  port: 5672
  fixtureQueue: power-lines-fixtures
  resultQueue: power-lines-results

cronJob:
  schedule: "0 9,10,11,12,13,14,15,16,17 * * *"
  resultsAllSchedule: "0 0 1 * *"
  concurrencyPolicy: Forbid
  restartPolicy: Never

secret:
  secretsPath: /power-lines-data-service
