environment: production
name: power-lines-data-service
image: power-lines-data-service

container:
  requestMemory: 60Mi
  requestCpu: 60m
  limitMemory: 250Mi
  limitCpu: 250m
  comPlusEnableDiagnostics: 0  
  command: ["dotnet"]
  args: ["PowerLinesDataService.dll", "--fixtures"]
  resultsArgs: ["PowerLinesDataService.dll", "--results"]
  resultsAllArgs: ["PowerLinesDataService.dll", "--results", "--all"]

message:
  host: services.lynxmagnus.com
  port: 5672
  fixtureQueue: power-lines-fixtures
  resultQueue: power-lines-results

cronJob:
  schedule: "0 12,13,14,15,16,17 * * *"
  resultsAllSchedule: "0 0 1 * *"
  concurrencyPolicy: Forbid
  restartPolicy: Never
