environment: development
name: power-lines-data-service
image: power-lines-data-service

container:
  imagePullPolicy: IfNotPresent
  requestMemory: 60Mi
  requestCpu: 60m
  limitMemory: 250Mi
  limitCpu: 250m
  readOnlyRootFilesystem: false
  allowPrivilegeEscalation: false
  comPlusEnableDiagnostics: 0  
  command: ["dotnet"]
  args: ["PowerLinesDataService.dll", "--fixtures"]
  resultsArgs: ["PowerLinesDataService.dll", "--results"]
  resultsAllArgs: ["PowerLinesDataService.dll", "--results", "--all"]

message:
  host: host.docker.internal
  port: 5672
  fixtureQueue: power-lines-fixtures
  fixtureUsername: rabbitmq
  fixturePassword: rabbitmq
  resultQueue: power-lines-results
  resultUsername: rabbitmq
  resultPassword: rabbitmq

cronJob:
  schedule: "0 12,13,14,15,16,17 * * *"
  resultsAllSchedule: "0 12,13,14,15,16,17 * * *"
  concurrencyPolicy: Forbid
  restartPolicy: Never
